# Generated by Django 3.1.6 on 2023-05-30 08:52

from django.db import migrations, models
import ocr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=ocr.models.get_file_path)),
            ],
        ),
    ]
